kind: pipeline
type: docker
name: build

trigger:
  event:
    - cron
    - custom

steps:
  - name: build
    image: node:20-alpine
    commands:
      - cd app
      - npm install
      - npm run build
      - tar -czf app-build.tar.gz dist

  - name: UnitTest
    image: alpine
    commands:
      - echo "deploying..."

  - name: CodeQuality
    image: alpine
    commands:
      - echo "deploying..."

  - name: Publish
    image: alpine
    commands:
      - echo "deploying..."

---
kind: pipeline
type: docker
name: SystemIntegrationTest

depends_on:
  - build

trigger:
  event:
    - cron
    - custom

steps:
  - name: SystemIntegrationTest
    image: alpine
    commands:
      - echo "deploying..."

---
kind: pipeline
type: docker
name: deploy

depends_on:
  - SystemIntegrationTest

trigger:
  event:
    - cron
    - custom

steps:
  - name: deploy
    image: alpine
    commands:
      - echo "deploying..."
