steps:
  build:
    image: node:20-alpine
    commands:
      - cd app
      - npm install
      - npm run build
    when:
      event: deployment
      evaluate: CI_PIPELINE_DEPLOY_TARGET == "build"

  deploy:
    image: alpine
    commands:
      - echo "deploying..."
    when:
      event: deployment
      evaluate: CI_PIPELINE_DEPLOY_TARGET == "deploy"