steps:
  build:
    image: node:20-alpine
    commands:
      - cd app
      - npm install
      - npm run build
    when:
      event: manual
      environment: build

  deploy:
    image: alpine
    commands:
      - echo "deploying..."
    when:
      event: manual
      environment: deploy